########################################################################################################
# ___                         ____                          __               __                        #
#/\_ \                       /\  _`\                       /\ \__           /\ \                       #
#\//\ \      ___      __     \ \ \/\_\     __      _____   \ \ ,_\    ___   \ \ \___       __          #
#  \ \ \    / __`\  /'_ `\    \ \ \/_/_  /'__`\   /\ '__`\  \ \ \/   /'___\  \ \  _ `\   /'__`\        #
#   \_\ \_ /\ \L\ \/\ \L\ \    \ \ \L\ \/\ \L\.\_ \ \ \L\ \  \ \ \_ /\ \__/   \ \ \ \ \ /\ \L\.\_      #
#   /\____\\ \____/\ \____ \    \ \____/\ \__/.\_\ \ \ ,__/   \ \__\\ \____\   \ \_\ \_\\ \__/.\_\     #
#   \/____/ \/___/  \/___L\ \    \/___/  \/__/\/_/  \ \ \/     \/__/ \/____/    \/_/\/_/ \/__/\/_/     #
#                     /\____/                        \ \_\                                             #
#                     \_/__/                          \/_/                                             #
########################################################################################################
#Thank you for downloading logCaptcha!
#Before you start to configurate this plugin, please read this text.
#If you don't understand what some option can do don't change it or read the texts above it.
#If you don't get it after that, and you definetly want to change it you can contact me on Spigot.
#This is important because if you change something wrong you can crash the complete plugin.
#
#Important: If you found any bugs please contact me. I'll help you and fix the bug as fast as I can!
#
#Okay, that should be it. Have fun to configurate this plugin! ^^
logCaptcha:

  #Prefixes for all!
  Prefix: '&clogCaptcha&7 |  '
  
  #Available languages: en-EN, de-DE
  #Default: en-EN
  Language: en-EN
  
  #Permissions for some commands
  Permissions:
    CaptchaCMD: logCaptcha.CaptchaCMD
    LogAdminCMD: logCaptcha.Admin
    LogBanCMD: logCaptcha.Admin
  
  #If that's is true, the plugin uses the custom captcha list. You can create custom
  #Questions and correct answers in the customCaptcha.yml file.
  #If you want to use color codes use '(paragraph)' instead of '&' in the file.
  #(This option is only for inventory captchas (for now).)
  #Attention: You need for every correct answer a question in the CORRECT ORDER
  #That means if your first entry at the question list is for example: Click on the Block named Zero
  #Then the first entry of the correct answer list MUST be Zero.
  #IF YOU USE CHAT CAPTCHA:
  #You can create custom words in the customCaptcha.yml file.
  #But ATTENTION: These custom words can not contain blank lines.
  #For example: CORRECT: Sample1 INCORRECT: Sample 1
  UseCustomCaptchas: false

  #Just some options
  Options:
    #The WaitingTime is the time (in seconds) the player has to solve the captcha
    #I recommend to set it to 35 if you use the raising captcha type and if you use
    #the chat captcha or the inventory captcha type set it to 20. But it's on you how
    #time you set.	
    WaitingTime: 35

    #The CheckCooldown is the cooldown that the "plugin wait" when a player joins.
    #After this time the plugin starts the check. Default is 1. (In seconds)
    CheckCooldown: 1

    #If that is true, you use the chat captcha method instead of the inventory method
    #In this method there is no support for bWaves and the player don't get kicked!
    UseChatCaptcha: false

    #If that's is true, you use the raising captcha method instead of the other methods
    UseRaisingCaptcha: false

    #If that is true, you use the inventory captcha method instead of the raising or chat method
    #This method is a simple method and I recommend it to use it instead of the chat method
    #InventoryCaptcha is currently disabled during some critical problems.

    #This method is like the chat captcha. But you click on the chat message, instead of 
    #type them in the chat. I would recommend it to use it instead of the chat captcha but it's on you.
    UseClickChatCaptcha: false

    #If that's is true the plugin will prevent players from interacting with items
    #(for example a lobby compass) so that they can't use them. I recommend to use it.	
    AntiRightlick: true

    #This captcha is a very easy type. I would recommend it if you want a very fast captcha type.
    #And I recommend to set the WaitingTime to about 10 or 15 because this type is really easy.
    #This is the default method
    UseSquareCaptcha: true

    #If that is true, the plugin will collect some statistics like how many players failed.
    #I recommend to use this, but if you don't want to use it it will not restrict any functions of the plugin.
    #(Except the logcaptcha stats command)
    UseStatistics: true

    #If that is true, the list which save all players who done the captcha already will get
    #cleared every 1200 seconds.
    #(Note: If you want to use this, you must enable the option SaveAlreadyDone!)
    ResetAlreadyDoneList: false

    #If that is true, every player which passed the captcha don't solve a captcha again
    #until he/she got removed from the list in Captcha.yml
    SaveAlreadyDone: false

    #If that is true, the plugin will ban a player automatically after 5 fails
    UseBWaves: false

    #If that true, then the plugin's own statistics are given in percent
    ShowStatisticsInPercent: true

    #ChatCaptcha options
    ChatCaptcha:
      #If this is true use randomized chars instead of words
      UseRandomizedChars: false

  #This is the build number to identify the exact version of the plugin
  #(If a release with no version number changes comes)
  Build: 142
  #Do not change this!
  Version: 1.1.3